#!/bin/bash

# Si la vérification (checkConf) est passée, récupère les dernières variables nécéssaires au script, depuis le fichier de conf repomanager.conf

EMAIL_DEST=$(grep "^EMAIL_DEST =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')
MANAGE_PROFILES=$(grep "^MANAGE_PROFILES =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')
REPO_CONF_FILES_PREFIX=$(grep "^REPO_CONF_FILES_PREFIX =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')

if [ "$OS_FAMILY" == "Redhat" ];then
    grep "^RELEASEVER =" "$CONF" | cut -d'=' -f2 > /etc/yum/vars/RELEASEVER
fi

GPG_SIGN_PACKAGES=$(grep "^GPG_SIGN_PACKAGES =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')

if [ "$GPG_SIGN_PACKAGES" == "yes" ];then
    GPG_KEYID=$(grep "^GPG_KEYID =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')
fi

UPDATE_AUTO=$(grep "^UPDATE_AUTO =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')
UPDATE_BRANCH=$(grep "^UPDATE_BRANCH =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')
UPDATE_BACKUP_ENABLED=$(grep "^UPDATE_BACKUP_ENABLED =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')
UPDATE_BACKUP_DIR=$(grep "^UPDATE_BACKUP_DIR =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')

WWW_USER=$(grep "^WWW_USER =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')
WWW_HOSTNAME=$(grep "^WWW_HOSTNAME =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')

DEFAULT_ENV=$(cat $ENV_CONF | grep -v '[ENVIRONNEMENTS]' | head -n1)
AUTOMATISATION_ENABLED=$(grep "^AUTOMATISATION_ENABLED =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')

if [ "$AUTOMATISATION_ENABLED" == "yes" ];then
    ALLOW_AUTOUPDATE_REPOS=$(grep "^ALLOW_AUTOUPDATE_REPOS =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')
    ALLOW_AUTOUPDATE_REPOS_ENV=$(grep "^ALLOW_AUTOUPDATE_REPOS_ENV =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')
    ALLOW_AUTODELETE_ARCHIVED_REPOS=$(grep "^ALLOW_AUTODELETE_ARCHIVED_REPOS =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')
    
    if [ "$ALLOW_AUTODELETE_ARCHIVED_REPOS" == "yes" ];then
        RETENTION=$(grep "^RETENTION =" "$CONF" | cut -d'=' -f2 | sed 's/"//g' | sed 's/ //g')
    fi
fi