---
description: CentOS official repositories
type: rpm
repositories:
  - name: centos-test
    type: rpm
    url: http://vault.centos.org/$releasever-stream/BaseOS/$basearch/os/
    releasever:
      - name: 8
        description: CentOS 8 Stream
        gpgkeys:

    ssl-authentication:
      certificate-path: ''
      private-key-path: ''
      ca-certificate-path: ''
