#!/bin/bash

# Si la vérification (checkConf) est passée, récupère les dernières variables nécéssaires au script, depuis le fichier de conf repomanager.conf

EMAIL_DEST=$(grep "^EMAIL_DEST=" "$CONF" | cut -d'=' -f2 | sed 's/"//g')
MANAGE_PROFILES=$(grep "^MANAGE_PROFILES=" "$CONF" | cut -d'=' -f2 | sed 's/"//g')
REPO_FILES_PREFIX=$(grep "^REPO_FILES_PREFIX=" "$CONF" | cut -d'=' -f2 | sed 's/"//g')

if [ "$OS_TYPE" == "Redhat" ];then
    grep "^RELEASEVER=" "$CONF" | cut -d'=' -f2 > /etc/yum/vars/RELEASEVER
    GPG_SIGN_PACKAGES=$(grep "^GPG_SIGN_PACKAGES=" "$CONF" | cut -d'=' -f2 | sed 's/"//g')

    if [ "$GPG_SIGN_PACKAGES" == "yes" ];then
        GPG_KEYID=$(grep "^GPG_KEYID=" "$CONF" | cut -d'=' -f2 | sed 's/"//g')
    fi
fi

WWW_ENABLED=$(grep "^WWW_ENABLED=" "$CONF" | cut -d'=' -f2 | sed 's/"//g')
if [ "$WWW_ENABLED" == "yes" ];then
    WWW_USER=$(grep "^WWW_USER=" "$CONF" | cut -d'=' -f2 | sed 's/"//g')
    WWW_HOSTNAME=$(grep "^WWW_HOSTNAME=" "$CONF" | cut -d'=' -f2 | sed 's/"//g')
fi

REPO_DEFAULT_ENV=$(cat $ENV_CONF_FILE | grep -v '[ENVIRONNEMENTS]' | head -n1)
AUTOMATISATION_ENABLED=$(grep "^AUTOMATISATION_ENABLED=" "$CONF" | cut -d'=' -f2 | sed 's/"//g')

if [ "$AUTOMATISATION_ENABLED" == "yes" ];then
    ALLOW_AUTOUPDATE_REPOS=$(grep "^ALLOW_AUTOUPDATE_REPOS=" "$CONF" | cut -d'=' -f2 | sed 's/"//g')
    ALLOW_AUTOUPDATE_REPOS_STATE=$(grep "^ALLOW_AUTOUPDATE_REPOS_STATE=" "$CONF" | cut -d'=' -f2 | sed 's/"//g')
    ALLOW_AUTODELETE_ARCHIVED_REPOS=$(grep "^ALLOW_AUTODELETE_ARCHIVED_REPOS=" "$CONF" | cut -d'=' -f2 | sed 's/"//g')
    
    if [ "$ALLOW_AUTODELETE_ARCHIVED_REPOS" == "yes" ];then
        RETENTION=$(grep "^RETENTION=" "$CONF" | cut -d'=' -f2 | sed 's/"//g')
    fi
fi


