#!/bin/bash

# La fonction a besoin de 4 paramètres pour fonctionner :
# Le nom du repo
# Le nom de la distribution
# Le nom de la section
# La date de la section
while [ $# -ge 1 ];do case "$1" in
	--repo-name)
		REPO_NAME="$2"
		shift
	;;
	--repo-dist)
		REPO_DIST="$2"
		shift
	;;
	--repo-section)
		REPO_SECTION="$2"
		shift
	;;
	--repo-date)
		REPO_DATE="$2"
		shift
	;;
	*)
	esac
	shift
done

# On vérifie que la section renseignée est bien présente dans le fichier repos-archive.list, si oui alors on peut commencer l'opération
if ! egrep -q "^Name=\"${REPO_NAME}\",Host=\".*\",Dist=\"${REPO_DIST}\",Section=\"${REPO_SECTION}\",Date=\"${REPO_DATE}\"" ${REPOS_ARCHIVE_LIST};then
	echo -e "\nErreur de syntaxe ou il n'existe aucune section archivée ${CYAN}${REPO_SECTION}${RESET} du repo ${CYAN}${REPO_NAME}${RESET} (distribution : ${REPO_DIST}) en date du ${CYAN}${REPO_DATE}${RESET} sur ce serveur..."
    clean_exit
fi

echo -e "\nDébut de l'opération" 
sleep 1

####

echo -ne "Suppression de la section archivée ${REPO_SECTION} :\t\t"
cd ${REPOS_DIR}/${REPO_NAME}/${REPO_DIST}/ &&
rm 99_old_version_${REPO_DATE}_${REPO_SECTION}/ -rf
echo -e "[$VERT OK $RESET]"

####

echo -ne "Mise à jour des informations dans repos-archive.list :\t"
sed -i /^Name=\"${REPO_NAME}\",Host=\".*\",Dist=\"${REPO_DIST//\//\\/}\",Section=\"${REPO_SECTION}\",Date=\"${REPO_DATE}\"/d $REPOS_ARCHIVE_LIST && # On supprime la section dans le fichier repos-archive.list
echo -e "[$VERT OK $RESET]"

echo -e "${VERT}Opération terminée${RESET}"