#!/bin/bash

# La fonction a besoin de 2 paramètres pour fonctionner :
# Le nom du repo
# La date du repo
while [ $# -ge 1 ];do case "$1" in
	--repo-name)
		REPO_NAME="$2"
		shift
	;;
	--repo-date)
		REPO_DATE="$2"
		shift
	;;
	*)
	esac
	shift
done

# On vérifie que le repo renseigné est bien présent dans le fichier repos-archive.list, si oui alors on peut commencer l'opération
if ! egrep -q "^Name=\"${REPO_NAME}\",Realname=\".*\",Date=\"${REPO_DATE}\"" $REPOS_ARCHIVE_LIST;then  # On vérifie que le repo renseigné est bien présent dans le fichier repos-archive.list, alors on peut commencer l'opération
	echo -e "\nErreur de syntaxe ou il n'existe aucun repo archivé ${CYAN}${REPO_NAME}${RESET} en date du ${CYAN}${REPO_DATE}${REST} sur ce serveur..."
    clean_exit
fi

echo -e "\nDébut de l'opération"
sleep 1

####

echo -ne "Suppression du repo archivé ${REPO_NAME} :\t"
cd ${REPOS_DIR}/ &&
rm 99_old_version_${REPO_DATE}_${REPO_NAME}/ -rf &&
echo -e "[${VERT} OK ${RESET}]"

####

echo -ne "Mise à jour des informations dans repos-archive.list :\t"
sed -i /^Name=\"${REPO_NAME}\",RealName=\".*\",Date=\"${REPO_DATE}\"/d $REPOS_ARCHIVE_LIST &&   # On supprime le repo dans le fichier repos-archive.list
echo -e "[${VERT} OK ${RESET}]"

echo -e "${VERT}Opération terminée${RESET}"