#!/bin/bash

# Supprime les fichiers de conf repo .list ou .repo lors de la suppression d'un repo/section
# Ces fichiers sont utilisés pour les profils et sont téléchargés par les serveurs/postes clients

while [ $# -ge 1 ];do
    case "$1" in
        --repo-name)
            REPO_NAME="$2"
            shift
        ;;
        --repo-dist)
            REPO_DIST="$2"
            shift
        ;;
        --repo-section)
            REPO_SECTION="$2"
            shift
        ;;
        *)
	esac
	shift
done

VAR_MISSING=0

if [ "$OS_TYPE" == "Debian" ];then
    if [ -z "$REPO_NAME" ] || [ -z "$REPO_DIST" ] || [ -z "$REPO_SECTION" ] || [ -z "${WWW_HOSTNAME}" ];then
        (( $VAR_MISSING++ ))
    fi

    if [ "$VAR_MISSING" -eq "0" ];then # on traite uniquement si il n'y a pas eu d'erreur
        rm -f "${REPOS_CONF_FILES_DIR}/${REPO_CONF_FILES_PREFIX}${REPO_NAME}_${REPO_DIST}_${REPO_SECTION}.list"
    fi
fi

if [ "$OS_TYPE" == "Redhat" ];then
    if [ -z "$REPO_NAME" ] || [ -z "${WWW_HOSTNAME}" ];then
        (( $VAR_MISSING++ ))
    fi

    if [ "$VAR_MISSING" -eq "0" ];then # on traite uniquement si il n'y a pas eu d'erreur
        rm -f "${REPOS_CONF_FILES_DIR}/${REPO_CONF_FILES_PREFIX}${REPO_NAME}.repo"
    fi
fi

if [ "$VAR_MISSING" -gt "0" ];then
    echo "[ ERREUR ] Impossible de supprimer le fichier de conf repo sur le serveur, une variable nécéssaire est vide"
fi