#!/bin/bash

ACTUAL_USER=$(whoami)

# On re-applique les permissions uniquement si on est root, sinon ça risque de renvoyer des erreurs "Permission denied"
if [ "$ACTUAL_USER" == "root" ];then
    # Droits sur le répertoire de repomanager
    chown -R ${WWW_USER}:repomanager ${BASE_DIR}
    find ${BASE_DIR}/ -type d -exec chmod 0770 {} \;
    find ${BASE_DIR}/ -type f -exec chmod 0660 {} \;
    chmod 770 ${BASE_DIR}/repomanager

    # Droits sur les fichiers de conf de repomanager
    find ${ETC_DIR}/ -type f -exec chmod 0660 {} \;
    find ${ETC_DIR}/ -type d -exec chmod 0770 {} \;
    chmod 775 ${ETC_DIR}
    chown -R root:repomanager ${ETC_DIR}

    # Droits sur le répertoire web
    find ${WWW_DIR} -type f -exec chmod 0660 {} \;
    find ${WWW_DIR} -type d -exec chmod 0770 {} \;
    chmod 775 ${WWW_DIR}
    chown -R ${WWW_USER}:repomanager ${WWW_DIR}

    # Droits sur le répertoire stockant les repos
    # Ici on ne réapplique pas les droits sur les fichiers avec find car le répertoire peut être très volumineux, on laisse la tâche cron régulière s'en charger en tâche de fond
    chown -R ${WWW_USER}:repomanager ${REPOS_DIR}

    # permissions sur le répertoire de .gnupg
    if [ -d "${BASE_DIR}/.gnupg" ];then
        chown -R ${WWW_USER}:repomanager ${BASE_DIR}/.gnupg
        chmod 700 ${BASE_DIR}/.gnupg
        # permissions sur la passphrase
        if [ -f "${BASE_DIR}/.gnupg/passphrase" ];then 
            chmod 660 ${BASE_DIR}/.gnupg/passphrase
        fi
    fi

    if [ -f "${REPOS_DIR}/${WWW_HOSTNAME}.pub" ];then
        chown ${WWW_USER}:repomanager ${REPOS_DIR}/${WWW_HOSTNAME}.pub
		chmod 440 ${REPOS_DIR}/${WWW_HOSTNAME}.pub
    fi
    
    # permissions sur le répertoire des profils
    if [ -d "${PROFILES_MAIN_DIR}/" ];then
        chown -R ${WWW_USER}:repomanager ${PROFILES_MAIN_DIR}/
        find ${PROFILES_MAIN_DIR}/ -type f -exec chmod 0660 {} \;
        find ${PROFILES_MAIN_DIR}/ -type d -exec chmod 0770 {} \;
    fi

    if [ "$OS_FAMILY" == "Redhat" ];then
        chown root:repomanager /etc/yum/vars/RELEASEVER
        chmod 660 /etc/yum/vars/RELEASEVER
        # permissions sur repomanager et ses fichiers de conf
        if [ -d "$REPOMANAGER_YUM_DIR" ];then
            chown -R ${WWW_USER}:repomanager "$REPOMANAGER_YUM_DIR"
            find ${REPOMANAGER_YUM_DIR}/ -type f -exec chmod 0664 {} \;
            chmod 775 "$REPOMANAGER_YUM_DIR"
        fi
        # permissions sur /etc/pki/rpm-gpg/repomanager
        if [ -d "$RPM_GPG_DIR" ];then
            chown -R root:repomanager "$RPM_GPG_DIR"
            find ${RPM_GPG_DIR}/ -type f -exec chmod 0664 {} \;
            chmod 775 "$RPM_GPG_DIR"
        fi

        # permissions sur les fichiers du module rpmresign (perl/RPM4)
        # Donner le droit à WWW_USER de rentrer dans les répertoires suivants, liés au module perl RPM4 :
        if [ -d "/usr/local/lib64/perl5/RPM4/" ];then
            chmod o+x /usr/local/lib64/perl5/RPM4
            find /usr/local/lib64/perl5/RPM4/ -type d -exec chmod o+x {} \;
            find /usr/local/lib64/perl5/RPM4/ -type f -exec chmod o+r {} \;
        fi
        if [ -d "chmod o+x /usr/local/lib64/perl5/auto" ];then 
            chmod o+x /usr/local/lib64/perl5/auto
        fi
        if [ -d "/usr/local/lib64/perl5/auto/RPM4" ];then
            chmod o+x /usr/local/lib64/perl5/auto/RPM4
        fi
        if [ -d "chmod o+x /usr/local/lib64/perl5" ];then
            chmod o+x /usr/local/lib64/perl5
        fi
        if [ -f "/usr/local/lib64/perl5/RPM4.pm" ];then
            chmod o+r /usr/local/lib64/perl5/RPM4.pm
        fi
    fi
fi