#!/bin/bash

# On tri les fichiers par ordre alpha et on écrit le résultat dans le même fichier
sort -o $REPOS_LIST $REPOS_LIST
if [ -f "$HOSTS_CONF" ];then 
    sort -o $HOSTS_CONF $HOSTS_CONF
fi
if [ -f "$REPOS_ARCHIVE_LIST" ];then
    sort -o $REPOS_ARCHIVE_LIST $REPOS_ARCHIVE_LIST
fi