<?php

namespace Controllers\Task;

use Exception;

class Listing
{
    private $model;

    public function __construct()
    {
        $this->model = new \Models\Task\Listing();
    }

    /**
     *  Get all tasks
     */
    public function get(): array
    {
        return $this->model->get();
    }

    /**
     *  Get all queued tasks
     *  It is possible to filter the type of task ('immediate' or 'scheduled')
     *  It is possible to add an offset to the request
     */
    public function getQueued(string $type = '', bool $withOffset = false, int $offset = 0): array
    {
        return $this->model->getQueued($type, $withOffset, $offset);
    }

    /**
     *  Get all running tasks
     *  It is possible to filter the type of task ('immediate' or 'scheduled')
     *  It is possible to add an offset to the request
     */
    public function getRunning(string $type = '', bool $withOffset = false, int $offset = 0): array
    {
        return $this->model->getRunning($type, $withOffset, $offset);
    }

    /**
     *  Get all scheduled tasks
     *  It is possible to add an offset to the request
     */
    public function getScheduled(bool $withOffset = false, int $offset = 0): array
    {
        return $this->model->getScheduled($withOffset, $offset);
    }

    /**
     *  Get all done tasks (with or without errors)
     *  It is possible to filter the type of task ('immediate' or 'scheduled')
     *  It is possible to add an offset to the request
     */
    public function getDone(string $type = 'immediate', bool $withOffset = false, int $offset = 0): array
    {
        return $this->model->getDone($type, $withOffset, $offset);
    }

    /**
     *  Get all sub-tasks generated by a parent task
     *  It is possible to add an offset to the request
     */
    public function getByParentId(int $parentTaskId, bool $withOffset = false, int $offset = 0): array
    {
        return $this->model->getByParentId($parentTaskId, $withOffset, $offset);
    }

    /**
     *  Count sub-tasks generated by a parent task, grouped by status
     */
    public function countStatusByParentId(int $parentTaskId): array
    {
        return $this->model->countStatusByParentId($parentTaskId);
    }

    /**
     *  Return a summary of the sub-tasks statuses of a parent task
     *  A parent task has no status of its own as it only dispatches sub-tasks, so its real status is a summary of theirs
     *  Return an empty array if the task has no sub-task
     */
    public function getSubTasksSummary(int $parentTaskId): array
    {
        $count = $this->countStatusByParentId($parentTaskId);

        if (empty($count)) {
            return [];
        }

        return $this->buildSubTasksSummary($count);
    }

    /**
     *  Same as getSubTasksSummary() but for multiple parent tasks at once
     *  Tasks having no sub-task are not returned
     */
    public function getSubTasksSummaries(array $parentTaskIds): array
    {
        $summaries = [];

        foreach ($this->model->countStatusByParentIds($parentTaskIds) as $parentTaskId => $count) {
            $summaries[$parentTaskId] = $this->buildSubTasksSummary($count);
        }

        return $summaries;
    }

    /**
     *  Build a sub-tasks summary from a count of sub-tasks per status
     */
    private function buildSubTasksSummary(array $count): array
    {
        $summary = [
            'total'   => array_sum($count),
            'success' => $count['done'] ?? 0,
            'failed'  => ($count['error'] ?? 0) + ($count['stopped'] ?? 0),
            'ongoing' => ($count['running'] ?? 0) + ($count['queued'] ?? 0)
        ];

        if ($summary['ongoing'] > 0) {
            $summary['status'] = 'running';
        } elseif ($summary['failed'] > 0) {
            $summary['status'] = 'error';
        } else {
            $summary['status'] = 'done';
        }

        return $summary;
    }
}
