<?php
use \Controllers\Task\Task;
use \Controllers\App\DebugMode;
use \Controllers\User\Permission\Task as TaskPermission; ?>

<div class="flex align-item-center column-gap-15 justify-space-between">
    <div class="flex align-item-center column-gap-30">
        <h3>TASK #<?= $taskId ?></h3>

        <?php
        // If the task has been generated by another task, print a link to it
        if (!empty($taskInfo['Parent_task_id'])) : ?>
            <a href="/task/<?= $taskInfo['Parent_task_id'] ?>" title="View the scheduled task that generated this task"><p id="stop-task-log-btn" class="label-white pointer" task-id="<?= $taskId ?>">View parent task</p></a>
            <?php
        endif; ?>
    </div>

    <?php
    // Print the stop button if the task is running and the user has permission to stop it
    if ($taskInfo['Status'] == 'running') :
        if (TaskPermission::allowedAction('stop')) : ?>
            <p id="stop-task-log-btn" class="label-red stop-task-btn pointer" task-id="<?= $taskId ?>" title="Stop the task">Stop</p>
            <?php
        endif;
    endif ?>
</div>

<div id="task-refresh-container" task-id="<?= $taskId ?>" task-status="<?= $taskInfo['Status'] ?>" <?php echo ($legacyLog === true) ? 'legacy="true"' : '' ?>>
    <div class="flex flex-wrap align-item-center column-gap-15 row-gap-15 margin-bottom-15 kpi-container">
        <?php
        $statusText = ucfirst($taskInfo['Status']);
        $statusLabel = 'Status';

        if ($taskInfo['Status'] == 'done') {
            $statusText = 'Success'; // Override status text for better readability
            $icon = 'check';
            $accent = 'green';
        } elseif ($taskInfo['Status'] == 'error') {
            $statusText = 'Failed'; // Override status text for better readability
            $icon = 'warning-red';
            $accent = 'red';
        } elseif ($taskInfo['Status'] == 'stopped') {
            $icon = 'warning-red';
            $accent = 'red';
        } elseif ($taskInfo['Status'] == 'scheduled') {
            $icon = 'time';
            $accent = 'yellow';
        } elseif ($taskInfo['Status'] == 'running') {
            $icon = 'loading';
            $accent = 'cyan';
        }

        /**
         *  If the task has sub-tasks, its own status is meaningless as it only dispatched them,
         *  so the status displayed is a summary of the sub-tasks statuses
         */
        if (!empty($subTasksSummary)) {
            $statusText = 'Success ' . $subTasksSummary['success'] . '/' . $subTasksSummary['total'];

            if ($subTasksSummary['status'] == 'running') {
                $icon = 'loading';
                $accent = 'cyan';
            } elseif ($subTasksSummary['status'] == 'error') {
                $icon = 'warning-red';
                $accent = 'red';
            } else {
                $icon = 'check';
                $accent = 'green';
            }
        } ?>

        <div class="kpi-card kpi-accent-<?= $accent ?>">
            <img src="/assets/icons/<?= $icon ?>.svg" class="icon-np icon-medium" title="<?= $statusText ?>" />

            <div>
                <p class="kpi-value"><?= !empty($rawParams['action']) ? Task::generateLiteralAction($taskInfo)['title'] : 'Unknown action' ?></p>
                <p class="mediumopacity-cst">Action</p>
            </div>

            <?php
            if ((DEVEL or DebugMode::enabled()) and file_exists(MAIN_LOGS_DIR . '/repomanager-task-' . $taskId . '-log.process')) {
                echo '<img src="/assets/icons/file.svg" class="icon view-task-process-log margin-left-auto" task-id="' . $taskId . '" title="Debug log" />';
            } ?>
        </div>

        <?php
        // A task that has never been executed yet (e.g. a scheduled task) has no date
        $taskDate = !empty($taskInfo['Date']) ? DateTime::createFromFormat('Y-m-d', $taskInfo['Date']) : false;

        if ($taskDate !== false) : ?>
            <div class="kpi-card">
                <img src="/assets/icons/calendar.svg" class="icon-np icon-medium" />
                <div>
                    <p class="kpi-value"><?= $taskDate->format('d-m-Y') ?> <?= $taskInfo['Time'] ?></p>
                    <p class="mediumopacity-cst"><?= $taskInfo['Status'] == 'scheduled' ? 'Last execution' : 'Date' ?></p>
                </div>
            </div>
            <?php
        endif;

        if (!empty($taskInfo['Duration'])) : ?>
            <div class="kpi-card">
                <img src="/assets/icons/time.svg" class="icon-np icon-medium" />
                <div>
                    <p class="kpi-value"><?= $taskInfo['Duration'] ?></p>
                    <p class="mediumopacity-cst">Total duration</p>
                </div>
            </div>
            <?php
        endif ?>
    </div>

    <?= $output ?>
</div>

<div id="scroll-btns-container">
    <div id="scroll-btns">
        <?php
        // Print the auto scroll button if the task is running
        if ($taskInfo['Status'] == 'running') : ?>
            <div class="pointer margin-bottom-15">
                <?php
                $autoscroll = 'true';

                if (!empty($_COOKIE['autoscroll'])) {
                    $autoscroll = $_COOKIE['autoscroll'];
                }

                if ($autoscroll == 'true') : ?>
                    <div id="autoscroll-btn" class="round-btn-yellow" title="Disable auto refresh and scroll">
                        <span class="round-btn-icon" style="--icon: url('/assets/icons/pause.svg')"></span>
                    </div>
                    <?php
                else : ?>
                    <div id="autoscroll-btn" class="round-btn-green" title="Enable auto refresh and scroll">
                        <span class="round-btn-icon" style="--icon: url('/assets/icons/play.svg')"></span>
                    </div>
                    <?php
                endif ?>
            </div>
            <?php
        endif ?>
    </div>
</div>