#!/usr/bin/env bash
set -u
trap 'kill 0' EXIT

# Leave a delay of 30sec to let the system start
sleep 30

SCRIPT_PATH=$(realpath $0)
DATA_DIR="/var/lib/repomanager"
DB="$DATA_DIR/db/repomanager.db"
LOG_DIR="$DATA_DIR/logs/service"
LOG="$LOG_DIR/repomanager-service.log"
STATS_LOG_DIR="$DATA_DIR/logs/stats"
STATS_LOG="$STATS_LOG_DIR/stats-log-parser.log"
STATS_DB="$DATA_DIR/db/repomanager-stats.db"
CURRENT_TIME=""
LAST_TIME=""
STATS_LOG_PARSING_RUNNING="false"
COUNTER="0"

# Create log dirs if not exist
mkdir -p "$LOG_DIR"
mkdir -p "$STATS_LOG_DIR"

# Get additionnal variables
function getVars
{
    # Check is database exists
    while [ ! -f "$DB" ]; do
        echo "Error: Database '$DB' not found."
        sleep 3
    done

    WWW_DIR=$(/usr/bin/sqlite3 -noheader -batch -cmd '.timeout 10000' "$DB" "SELECT WWW_DIR FROM settings" | sed 's/ //g')
    WWW_USER=$(/usr/bin/sqlite3 -noheader -batch -cmd '.timeout 10000' "$DB" "SELECT WWW_USER FROM settings" | sed 's/ //g')
    REPOS_DIR=$(/usr/bin/sqlite3 -noheader -batch -cmd '.timeout 10000' "$DB" "SELECT REPOS_DIR FROM settings" | sed 's/ //g')
    UPDATE_BRANCH=$(/usr/bin/sqlite3 -noheader -batch -cmd '.timeout 10000' "$DB" "SELECT UPDATE_BRANCH FROM settings" | sed 's/ //g')
    STATS_ENABLED=$(/usr/bin/sqlite3 -noheader -batch -cmd '.timeout 10000' "$DB" "SELECT STATS_ENABLED FROM settings" | sed 's/ //g')
    # Access log file to analyze
    STATS_LOG_PATH=$(/usr/bin/sqlite3 -noheader -batch -cmd '.timeout 10000' "$DB" "SELECT STATS_LOG_PATH FROM settings" | sed 's/ //g')
    PLANS_ENABLED=$(/usr/bin/sqlite3 -noheader -batch -cmd '.timeout 10000' "$DB" "SELECT PLANS_ENABLED FROM settings" | sed 's/ //g')
    PLANS_REMINDERS_ENABLED=$(/usr/bin/sqlite3 -noheader -batch -cmd '.timeout 10000' "$DB" "SELECT PLANS_REMINDERS_ENABLED FROM settings" | sed 's/ //g')
}

# Check if this service needs to be restarted
function checkRestartNeeded
{
    if [ -f "$DATA_DIR/service.restart" ];then
        echo "A restart of this service is required. Restarting..."
        systemctl --quiet daemon-reload
        rm "$DATA_DIR/service.restart" -f
        exec systemctl --quiet restart repomanager
    fi
}

function generalChecks
{
    # Check if www user is defined
    if [ -z "$WWW_USER" ];then
        echo "Error: www user is not defined."
        exit 1
    fi

    # Check if www user is a reel unix user
    if ! grep -q "$WWW_USER" /etc/passwd;then
        echo "Error: www user is not a unix user."
        exit 1
    fi

    # Check if repos directory exists
    if [ ! -d "$REPOS_DIR" ];then
        echo "Error: Repos directory '$REPOS_DIR' not found."
        exit 1
    fi
}

# Clean temporary files and directories
function cleanUp
{
    # Clean files older than 7 days in .temp
    if [ -d "$DATA_DIR/.temp" ];then
        find "$DATA_DIR/.temp"/ -mtime +7 -exec rm -rf {} \;
    fi

    # Clean pid files older than 7 days
    if [ -d "$DATA_DIR/operations/pid/" ];then
        find "$DATA_DIR/operations/pid"/ -name *".pid" -mtime +7 -exec rm -f {} \;
    fi

    # Clean pool files older than 7 days
    if [ -d "$DATA_DIR/operations/pool/" ];then
        find "$DATA_DIR/operations/pool"/ -name *".json" -mtime +7 -exec rm -f {} \;
    fi

    # Clean temp mirror directories older than 7 days
    if [ -d "$REPOS_DIR" ];then
        find "$REPOS_DIR"/ -name "download-mirror-"* -type d -mtime +5 -exec rm -rf {} \;
    fi
}

# Check if a new version is available on Github
function checkVersion
{
    if [ ! -f "$DATA_DIR/version.available" ];then
        touch "$DATA_DIR/version.available"
        chown ${WWW_USER}:repomanager "$DATA_DIR/version.available"
    fi

    curl -s -H 'Cache-Control: no-cache' "https://raw.githubusercontent.com/lbr38/repomanager/${UPDATE_BRANCH}/www/version" > $DATA_DIR/version.available
}

# Apply permissions on repos directories
function applyPerms
{
    find "$REPOS_DIR" -type d -print0 | xargs -r0 chmod 0770
    find "$REPOS_DIR" -type f -print0 | xargs -r0 chmod 0660
    chown -R ${WWW_USER}:repomanager "$REPOS_DIR"
}

# Generate daily stats on repos such as package count and repo's size
function statsGenerate
{
    if [ "$CURRENT_TIME" == "$LAST_TIME" ];then
        return
    fi

    # Exit the function if time != 00:00
    if [ "$CURRENT_TIME" != "00:00" ];then
        return
    fi

    # Generate stats for each repos
    /usr/bin/su -s /bin/sh -c "/usr/bin/php $WWW_DIR/tools/stats-generator.php" "$WWW_USER" & > /dev/null
}

# Start parsing of access log to generete statistics on clients accessing the repos 
function statsParseAccessLog
{
    # Checks that required variables are set and that files exist
    if [ -z "$STATS_LOG_PATH" ];then
        echo "Error: Cannot determine access log file to analyze." >> "$LOG"
        return
    fi

    if [ ! -f "$STATS_LOG_PATH" ];then
        echo "Error: Access log file '$STATS_LOG_PATH' not found." >> "$LOG"
        return
    fi

    if [ ! -f "$STATS_DB" ];then
        echo "Error: Database '$STATS_DB' not found." >> "$LOG"
        return
    fi

    if [ ! -f "/usr/bin/sqlite3" ];then
        echo "Error: '/usr/bin/sqlite3' not found." >> "$LOG"
        return
    fi

    # Do not start log analyze if an analyze is already running
    if [ "$STATS_LOG_PARSING_RUNNING" == "false" ];then
        # Loop that get every new lines in the 'STATS_LOG_PATH' file
        # New lines are parsed to get date, time, IP and request
        tail -n0 -F "$STATS_LOG_PATH" | \
        while read LINE; do
            if echo "$LINE" | grep -q -E 'urlgrabber|APT-CURL|APT-HTTP';then
                # If a repomanager release update is running, then wait to don't alter the database
                while [ -f "${DATA_DIR}/update-running" ]; do
                    sleep 2
                done
                # Parse the line and insert in database
                DATE=$(echo "$LINE" | awk '{print $4}' | sed 's/\[//g' | cut -d':' -f1 | sed 's|/|-|g')
                DATE=$(date -d "$DATE" +%Y-%m-%d)
                TIME=$(echo "$LINE" | awk '{print $4}' | cut -d':' -f2,3,4)
                SOURCE_IP=$(echo "$LINE" | awk '{print $1}')
                SOURCE_HOST=$(dig -x $SOURCE_IP +short)
                REQUEST=$(echo "$LINE" | awk '{print $6,$7,$8}')
                REQUEST_RESULT=$(echo "$LINE" | awk '{print $9}')
                /usr/bin/sqlite3 -cmd ".timeout 5000" -cmd ".log '$STATS_LOG'" "$STATS_DB" "INSERT INTO access (Date, Time, Source, IP, Request, Request_result) VALUES ('$DATE', '$TIME', '$SOURCE_HOST', '$SOURCE_IP', '$REQUEST', '$REQUEST_RESULT');"
            fi
        done &

        STATS_LOG_PARSING_RUNNING="true"
    fi
}

# Clean old stats for each repos
function statsClean
{
    if [ ! -f "$STATS_DB" ];then
        echo "Error: Database '$STATS_DB' not found." >> "$LOG"
        return
    fi

    if [ ! -f "/usr/bin/sqlite3" ];then
        echo "Error: '/usr/bin/sqlite3' not found." >> "$LOG"
        return
    fi

    /usr/bin/su -s /bin/sh -c "/usr/bin/php $WWW_DIR/tools/stats-cleaner.php" "$WWW_USER" & > /dev/null
}

# Execute plans every minute
function execPlan
{
    if [ "$CURRENT_TIME" == "$LAST_TIME" ];then
        return
    fi

    # Execute plans in background as www user
    /usr/bin/su -s /bin/sh -c "/usr/bin/php $WWW_DIR/operations/plan.php 'exec'" "$WWW_USER" & > /dev/null
}

# Send plan reminder (every day at 00:00)
function sendPlanReminder
{
    if [ "$CURRENT_TIME" == "$LAST_TIME" ];then
        return
    fi

    # Exit the function if time != 00:00
    if [ "$CURRENT_TIME" != "00:00" ];then
        return
    fi

    # Execute plans in background as www user
    /usr/bin/su -s /bin/sh -c "/usr/bin/php $WWW_DIR/operations/plan.php 'send-reminders'" "$WWW_USER" & > /dev/null
}

# Get notifications
function getNotifications
{
    /usr/bin/su -s /bin/sh -c "/usr/bin/php $WWW_DIR/tools/get-notifications.php" "$WWW_USER" & > /dev/null
}

# Execution
while true; do

    # Get vars on every loop because their value can have been updated by user from the web interface
    getVars

    # Clean log
    echo -n> "$LOG"
    chown -R $WWW_USER "$LOG_DIR"
    chown -R $WWW_USER "$STATS_LOG_DIR"

    # Check that vars are defined
    generalChecks

    # Check if a restart of this service is needed
    checkRestartNeeded

    # Execute actions on service start (COUNTER = 0) and then every hour (COUNTER = 720)
    # 3600 / 5sec (sleep 5) = 720
    if [ "$COUNTER" -eq "0" ] || [ "$COUNTER" -eq "720" ];then
        # Check version
        checkVersion

        # Cleanup files
        cleanUp

        if [ "$STATS_ENABLED" == "true" ];then
            # Clean old statistics
            statsClean
        fi

        # Get notifications
        getNotifications

        # Reset counter
        COUNTER="0"
    fi

    CURRENT_TIME=$(date +%H:%M)

    # Parse access logs to generate stats (if enabled)
    if [ "$STATS_ENABLED" == "true" ];then
        statsGenerate
        statsParseAccessLog
    fi

    # Execute plans (if plan enabled)
    if [ "$PLANS_ENABLED" == "true" ];then
        execPlan
    fi

    # Send plans reminder (if plan and plan reminders enabled)
    if [ "$PLANS_ENABLED" == "true" ] && [ "$PLANS_REMINDERS_ENABLED" == "true" ];then
        sendPlanReminder
    fi

    LAST_TIME=$(date +%H:%M)

    sleep 5

    (( COUNTER++ ))
done

exit