#!/bin/bash
set -e

WWW_DIR="/var/www/repomanager"
DATA_DIR="/var/lib/repomanager"

# Docker environment variables
#  - FQDN=server.example.com
#  - MAX_UPLOAD_SIZE=xxM
#  - PHP_MEMORY_LIMIT=xxM
#  - NGINX_LISTEN_PORT=xxxx
#  - WEBSOCKET_LISTEN_PORT=xxxx
#  - PUID=xxxx
#  - PGID=xxxx

# Quit if FQDN is not set
if [ -z "$FQDN" ];then
    echo "FQDN environment variable must be set"
    exit 1
fi

# If no branch is set in environment, use main
if [ -z "$BRANCH" ];then
    BRANCH="main"
fi

# If custom PUID is set
if [ ! -z "$PUID" ];then
    # PUID must be >= 1000
    if [ "$PUID" -lt 1000 ];then
        echo "PUID must be greater than or equal to 1000"
        exit 1
    fi

    usermod -u "$PUID" www-data
fi

# If custom PGID is set
if [ ! -z "$PGID" ];then
    # PGID must be >= 1000
    if [ "$PGID" -lt 1000 ];then
        echo "PGID must be greater than or equal to 1000"
        exit 1
    fi

    groupmod -g "$PGID" www-data
fi

# Set FQDN
# Postfix/mail configuration
postconf -e "myhostname = $FQDN"
echo "$FQDN" > /etc/mailname
# Repomanager configuration
echo "$FQDN" > "$WWW_DIR/.fqdn"

# Set max upload size
if [ ! -z "$MAX_UPLOAD_SIZE" ];then
    # Nginx configuration
    sed -i "s/client_max_body_size.*$/client_max_body_size ${MAX_UPLOAD_SIZE};/g" /etc/nginx/sites-enabled/repomanager.conf
    # PHP configuration
    sed -i "s/^upload_max_filesize.*$/upload_max_filesize = ${MAX_UPLOAD_SIZE}/g" /etc/php/8.3/fpm/php.ini
    sed -i "s/^post_max_size.*$/post_max_size = ${MAX_UPLOAD_SIZE}/g" /etc/php/8.3/fpm/php.ini
fi

# Set PHP memory limit
if [ ! -z "$PHP_MEMORY_LIMIT" ];then
    sed -i "s/^memory_limit.*$/memory_limit = ${PHP_MEMORY_LIMIT}/g" /etc/php/8.3/fpm/php.ini
fi

# Set Nginx listen port
if [ ! -z "$NGINX_LISTEN_PORT" ];then
    sed -i "s/listen 8080;/listen ${NGINX_LISTEN_PORT};/g" /etc/nginx/sites-enabled/repomanager.conf
fi

# Set WebSocket server listen port
if [ ! -z "$WEBSOCKET_LISTEN_PORT" ];then
    sed -i "s/set \$WEBSOCKET_LISTEN_PORT.*;/set \$WEBSOCKET_LISTEN_PORT $WEBSOCKET_LISTEN_PORT;/g" /etc/nginx/sites-enabled/repomanager.conf
    # Also create a .wss file
    echo "$WEBSOCKET_LISTEN_PORT" > "$WWW_DIR/.wss"
fi

# If app.yaml does not exist, create it
if [ ! -f "$DATA_DIR/app.yaml" ];then
    cp "$WWW_DIR/templates/app.yaml" "$DATA_DIR/app.yaml"
fi

# If branch is devel
if [ "$BRANCH" == "devel" ];then
    # Create directory for XDebug
    mkdir -p /tmp/xdebug
    chown www-data:www-data /tmp/xdebug
    chmod 770 /tmp/xdebug

    # Create .devel file
    touch "$WWW_DIR/.devel"
fi

# Apply permissions
/bin/bash $WWW_DIR/bin/repomanager -p

# Start services
/usr/sbin/service php8.3-fpm start > /dev/null
/usr/sbin/service nginx start > /dev/null
/usr/sbin/service postfix start > /dev/null

# Initialize database
setpriv --reuid www-data --regid www-data --groups www-data,repomanager /usr/bin/php "$WWW_DIR/tools/database/initialize.php"

# Update database (if needed)
setpriv --reuid www-data --regid www-data --groups www-data,repomanager /usr/bin/php "$WWW_DIR/tools/database/update.php"

# Start repomanager service
setpriv --reuid www-data --regid www-data --groups www-data,repomanager /usr/bin/php "$WWW_DIR/tools/service.php" &

# Retrieve service.php PID
main_pid=$!

terminate() {
    # Stop repomanager service (service.php) by sending SIGTERM
    echo "Stopping repomanager service..."
    kill -s SIGTERM $main_pid

    echo "Stopping postfix..."
    /usr/sbin/service postfix stop > /dev/null

    echo "Stopping nginx..."
    /usr/sbin/service nginx stop > /dev/null

    echo "Stopping php-fpm..."
    /usr/sbin/service php8.3-fpm stop > /dev/null
    exit
}

# Catch termination signals and execute terminate() function
trap terminate TERM
wait
