DEFAULT_TIMEOUT: 15
DEFAULT_TEMPLATES_ROOT: ../www/templates/source-repositories
DEFAULT_RPM_ARCHITECTURES:
  - x86_64
  - aarch64
  - ppc64le
  - s390x
  - armv7hl
  - i686
IGNORED_TEMPLATE_NAMES:
  - deb-repository.yml.template
  - rpm-repository.yml.template
IGNORED_DEB_ARCHITECTURES:
  - all
  - source
IGNORED_DEB_SUITES:
  - experimental
  - testing
  - unstable
IGNORED_DEB_DIRECTORIES:
  - by-hash
  - partial
IGNORED_DEB_COMPONENTS:
  - nightly
  - test
MISSING_STATUS_CODES:
  - 404
  - 410
