#!/bin/bash
SCRIPT_PATH=$(realpath $0)
WWW_DIR=$(echo "$SCRIPT_PATH" | sed 's|/tools/stats-log-parser||g')
DB="${WWW_DIR}/db/repomanager-stats.db"
ACCESS_LOG_FILE="$1"

if [ ! -f "$ACCESS_LOG_FILE" ];then exit;fi
if [ ! -f "$DB" ];then exit;fi

tail -n0 -F "$ACCESS_LOG_FILE" | \
while read logline; do

    if echo "$logline" | grep -q -E 'urlgrabber|APT-CURL|APT-HTTP';then
        # Parsage de la ligne récupérée puis insertion en BDD
        if [ -f "/usr/bin/sqlite3" ];then
            DATE=$(echo "$logline" | awk '{print $4}' | sed 's/\[//g' | cut -d':' -f1 | sed 's|/|-|g')
            DATE=$(date -d "$DATE" +%Y-%m-%d)
            TIME=$(echo "$logline" | awk '{print $4}' | cut -d':' -f2,3,4)
            SOURCE_IP=$(echo "$logline" | awk '{print $1}')
            SOURCE_HOST=$(dig -x $SOURCE_IP +short)
            REQUEST=$(echo "$logline" | awk '{print $6,$7,$8}')
            REQUEST_RESULT=$(echo "$logline" | awk '{print $9}')

            /usr/bin/sqlite3 -init <(echo .timeout 6000) "$DB" "INSERT INTO access (Date, Time, Source, IP, Request, Request_result) VALUES ('$DATE', '$TIME', '$SOURCE_HOST', '$SOURCE_IP', '$REQUEST', '$REQUEST_RESULT');"
        fi
    fi
done

exit