<?php
$taskController = new \Controllers\Task\Task();
$taskListingController = new \Controllers\Task\Listing();
$reloadableTableOffset = 0;

// The parent task Id is the task Id currently displayed (/task/{id})
$parentTaskId = __ACTUAL_URI__[2];

// Retrieve offset from cookie if exists
if (!empty($_COOKIE['tables/tasks/list-children/offset']) and is_numeric($_COOKIE['tables/tasks/list-children/offset'])) {
    $reloadableTableOffset = $_COOKIE['tables/tasks/list-children/offset'];
}

// Get list of sub-tasks generated by the parent task, with offset
$reloadableTableContent = $taskListingController->getByParentId($parentTaskId, true, $reloadableTableOffset);

// Get list of ALL sub-tasks, without offset, for the total count
$reloadableTableTotalItems = count($taskListingController->getByParentId($parentTaskId));

// Count total pages for the pagination
$reloadableTableTotalPages = ceil($reloadableTableTotalItems / 10);

// Calculate current page number
$reloadableTableCurrentPage = ceil($reloadableTableOffset / 10) + 1;
