name: API - test-user2 - repository listing tests
description: Run repository listing tests as test-user2 user

inputs:
  api-host:
    description: API test host URL
    required: true
  api-key:
    description: test-user2 API key
    required: true

runs:
  using: composite
  steps:
    # List all repositories
    - name: List all repositories
      shell: bash
      run: |
        curl --fail-with-body -L -s -X GET -H "Authorization: Bearer ${{ inputs.api-key }}" ${{ inputs.api-host }}/api/v2/repo/ | jq

    # List all repositories with name "local-deb-for-test-user2"
    - name: List repositories with specific name
      shell: bash
      run: |
        curl --fail-with-body -L -s -X GET -H "Authorization: Bearer ${{ inputs.api-key }}" ${{ inputs.api-host }}/api/v2/repo/ | jq -r '.results[] | select(.Name == "local-deb-for-test-user2")'

    # List all snapshots of repository whose ID is 5
    - name: List snapshots of a repository
      shell: bash
      run: |
        curl --fail-with-body -L -s -X GET -H "Authorization: Bearer ${{ inputs.api-key }}" ${{ inputs.api-host }}/api/v2/repo/5
