name: Deploy documentation
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - run: pip install -r documentation/requirements.txt
      # - run: pip install mkdocs-material

      - run: |
          cd documentation
          mkdocs gh-deploy --strict --force
